### ISSUE TITLE
タイムテーブルを変更

### ISSUE THREAD

**Issue by yoshi522** [beyond-school/homepage#13]
https://docs.google.com/document/d/1lAF04MiNQ1eF2DjFQiyWXDOAVbOoY-wGMtSZuGcmNFo/edit

**Comment by yuki0624** [comment]
![dsc_0024](https://user-images.githubusercontent.com/27789660/27259245-50d6c1ae-5449-11e7-8083-4e75f39c15b5.jpg)
![dsc_0091](https://user-images.githubusercontent.com/27789660/27259246-584156a2-5449-11e7-9618-6f99dcd07cf7.jpg)
