### ISSUE TITLE
HOME<Beyond School

### ISSUE THREAD

**Issue by yuki0624** [beyond-school/homepage#32]
・BEYOND SCHOOLをBeyond Schoolに変更

・見出しである「BEYOND SCHOOL」と「事業内容」のフォント及びサイズを合わせて欲しい。
>フォントは、ロゴのものを使用して欲しい。

・Beyond Schoolは、「本気の学生を溢れさせる」というビジョンのもと、現役大学生×社会人を学校現場に派遣し、中高生に多様な選択肢と自分の「したい」に出会える場・きっかけを提供する教育事業を手掛けています。

>夜会人になっているので変更お願い。
>もう少し濃い色にして欲しい
>フォントサイズをあと少し大きくして欲しい。

・上に準じて事業内容の説明文のフォントも色も全て合わせて欲しい。

**Comment by yoshi522** [comment]
> 見出しである「BEYOND SCHOOL」と「事業内容」のフォント及びサイズを合わせて欲しい。 
これは同じ。

> フォントは、ロゴのものを使用して欲しい。
フォントの種類は？

**Comment by yuki0624** [comment]
フォントの種類分かんね笑
調べれるやつなんやっけ？
柴ちゃんが巧みに使ってるアプリケーション
