### ISSUE TITLE
トップページ Beyond School 説明文変更

### ISSUE THREAD

**Issue by yuki0624** [beyond-school/homepage#37]
(変更前)
Beyond School
Beyond Schoolは、「本気の学生を溢れさせる」というビジョンのもと、現役大学生×社会人を学校現場に派遣し、中高生に多様な選択肢と自分の「したい」に出会える場・きっかけを提供する教育事業を手掛けています。

-----------------
(変更後)
Beyond School
Beyond Schoolは「次世代を担う若者が、自らの可能性を拓く社会を実現する」というビジョンのもと、若者が多様な選択肢に出会い、自分の意志を育む場を提供する教育事業を手掛けております。

**Comment by yoshi522** [comment]
変更したよ、確認してね
