### ISSUE TITLE
新聞をタイトルページに貼る

### ISSUE THREAD

**Issue by Koyo528206** [beyond-school/homepage#59]
https://drive.google.com/open?id=0ByfxfWk1KdDPLV9GVEc2VlFMU00
このリンクの新聞投稿をタイトルページに貼る

＝タイトルページの位置＝
　　　写真
　　  説明文
　　事業内容
動画　　　Facebook
新聞

**Comment by yuki0624** [comment]
これなしやね。景観を損なう！笑
左の欄に、「ポートフォリオ」っていう枠作れる？
そこに動画とか新聞記事乗せていきたい！
