### ISSUE TITLE
事業内容の上に Beyond School という row を追加

### ISSUE THREAD

**Issue by yoshi522** [beyond-school/homepage#6]
Beyond Schoolは、「本気の学生を溢れさせる」というビジョンのもと、現役大学生×夜会人を学校現場に派遣し、中高生に多様な選択肢と自分の「したい」に出会える場・きっかけを提供する教育事業を手掛けています。

**Comment by yuki0624** [comment]
![19340114_1926849770929321_1631213819_o](https://user-images.githubusercontent.com/27789660/27259287-2cc25868-544a-11e7-8f29-5790702858a8.png)

イメージこんな感じ
オレンジに白い文字で

**Comment by yoshi522** [comment]
![fireshot capture 3 - beyond school - http___127 0 0 1_8887_index html](https://user-images.githubusercontent.com/10850668/27506268-0dc1cd54-58f0-11e7-860e-61490842cf8c.png)
こんなんだけど？

**Comment by yuki0624** [comment]
いい感じ！！！！！！！！！
