### ISSUE TITLE
団体概要ページのVISION・MISSIONを修正

### ISSUE THREAD

**Issue by Koyo528206** [beyond-school/homepage#61]
【変更前】
VISION
「本気の学生を溢れさせる。」
MISSION
「多様な選択肢と自分の「したい」に出会えるきっかけを提供する。」
ーーーーーーーーーーーーー
【変更後】
VISION
「次世代を担う若者が、自らの可能性を拓く社会を実現する。」
MISSION
「若者が多様な選択肢に出会い、自分の意志を育む場を提供する。」

**Comment by Hiromu88** [comment]
更新完了、確認よろしく
