### ISSUE TITLE
ワークショップ@順天高校

### ISSUE THREAD

**Issue by Koyo528206** [beyond-school/homepage#63]
今回は順天高等学校にて、運営本部より3名、関東支部からサポーター6名を派遣し、中学生・高校生総勢25名の生徒さんを対象にキャリアワークショップを開催しました。 学生からは「同級生には進路がはっきり見えている人が多く焦っていたが、大学生の話を聞いて冷静に見つめなおすことができた。」、「夢は決まっていたが、本当にこれでいいのか、ともう一度考えるきっかけになった。」先生からは「生徒自身が自分のことを語っている姿や、自分の将来を考え始めている様子を見て、とても役に立ったと感じた。」など嬉しいお言葉をいただきました。実際に参加してみて、学生の反応も非常に良く、非常に白熱し、インタラクティブな交流が行われました。

ーーーーー
11月7日(火)
【ワークショップ】
順天高校
【キャリア】
![zyunten](https://user-images.githubusercontent.com/33190813/32844325-6fff737c-ca65-11e7-9f58-6f5944afef65.jpg)

**Comment by Hiromu88** [comment]
更新完了、確認よろしく
